# Defines stages which are to be executed
stages:
  - deploy
  - compile-assets
  
# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
Deploy:
  stage: deploy
  script:
  - >
     cd $SERVER_DIR_WWW 
     && sudo git pull 
     && sudo ln -sf $SERVER_DIR_V1 v1 
     && sudo ln -sf $SERVER_DIR_HOVERGAME hovergame 
     && exit
  only:
  - master

Compile SCSS:
  stage: compile-assets
  script:
  - >
     cd $SERVER_DIR_WWW/assets/css 
     && sudo sass --update styles.scss:styles.css
     && sudo sass --update print.scss:print.css
     && exit
  only:
  - master