[build]
  publish = "." # This tells Netlify to serve files from the current directory (root)
  command = ""  # No build command needed since it's a static site

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200